from solfege.note.with_tonic.chromatic import ChromaticNoteWithFundamental
from solfege.note.with_tonic.diatonic import DiatonicNoteWithFundamental
from solfege.note.with_tonic.note import NoteWithTonic

ChromaticNoteWithFundamental.RelatedDiatonicClass = DiatonicNoteWithFundamental
DiatonicNoteWithFundamental.RelatedChromaticClass = ChromaticNoteWithFundamental
ChromaticNoteWithFundamental.RelatedSolfegeClass = NoteWithTonic
