from instruments.fretted_instrument.position import generate
from instruments.fretted_instrument.note import generate_fretted_notes
from instruments.fretted_instrument.pair import generate
from instruments.fretted_instrument.scale import generate_guitar